# For development environment
FROM node:20.11-alpine3.18
USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./
CMD [ "npm", "run", "dev" ]
########################################
# Build image
# docker build -f Dockerfile.dev -t mgalvizo/docker-frontend-wsl:latest .
# Run image
# ~ alias is the home directory
# docker run -p 5173:5173 -v /home/node/app/node_modules -v ~/docker-frontend-wsl:/home/node/app mgalvizo/docker-frontend