version: "3"
services:
  web:
    build:
      # Override docker file selection
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
#################################################
# Run the containers
# docker-compose up
# Rebuild images
# docker-compose up --build
